version: '2'

volumes:
  vtiger-database:
  vtiger-defaultconfig:
  vtiger-localhostcert:
  vtiger-localhostkey:
  vtiger-app:
  vtiger-volume:
  vtiger-config_override:


services:

  nginx:
    image: nginx:1.16.1-alpine
    ports:
      - 80:80
    volumes:
      - vtiger-defaultconfig:/etc/nginx/conf.d/default.conf
      - vtiger-localhostcert:/etc/ssl/localhost.cert
      - vtiger-localhostkey:/etc/ssl/localhost.key
    links:
      - vtiger

  mysql:
    build: ./mysql
    volumes:
    - vtiger-database:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=mioga100Prozent
      - MYSQL_DATABASE=vtiger
      - MYSQL_USER=vtiger
      - MYSQL_PASSWORD=77777777


  vtiger:
    image: javanile/vtiger:6.5.0
    environment:
      - VT_DEBUG=true
      - VT_SITE_URL=https://58c47389e554a92c8673e510b28a94e9.balena-devices.com/
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=mioga100Prozent
    ports:
      - 8080:80
    volumes:
      - vtiger-app:/app
      - vtiger-volume:/var/lib/vtiger
      - vtiger-config_override:/var/www/html/config_override.php
    links:
      - mysql


  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "8081:8080"


