version: "2.0"
volumes:
  mysql:
services:
  mysql:
    build: ./mysql
    network_mode: host
  php:
    build: ./php
    network_mode: host
  apache:
    build: ./apache
    network_mode: host
    ports:
      - "80:80"

  adminer:
    image: adminer
    ports:
    - 8181:8080